# Generated by Django 6.0.4 on 2026-06-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_live'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
