# Generated by Django 6.0.4 on 2026-06-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instagram_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
