# Generated by Django 6.0.4 on 2026-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_instagram_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
